#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Extract the component fact sheet and component process fidelity sheet
# 2014/7/17
# Yasutaka Shirai

extractComponentFact <- function(con, currentDirectory)
{

# Get necessary data records from SEMPRE
tab_wbs_info<-dbGetQuery(con, "select wbs_element_key,replace(wbs_element_name, \",\",\".\") as wbs_element_name from pacedb.wbs_element where wbs_element_key != 1 order by wbs_element_key")
tab_project_info<-dbGetQuery(con,"select distinct wbs_element.wbs_element_key, project_key from pacedb.plan_item_hist right join pacedb.wbs_element on pacedb.plan_item_hist.wbs_element_key = pacedb.wbs_element.wbs_element_key where pacedb.wbs_element.wbs_element_key != 1 order by wbs_element_key")
tab_process_info<-dbGetQuery(con, "select distinct wbs_element_key,pacedb.phase.process_key,process_name from pacedb.plan_item_hist left join pacedb.phase on pacedb.plan_item_hist.phase_key = pacedb.phase.phase_key left join pacedb.process on pacedb.phase.process_key = pacedb.process.process_key where pacedb.phase.process_key is not null")
tab_teams_info<-dbGetQuery(con, "select distinct wbs_element_key, pacedb.data_block.team_key, REPLACE(team_name, \",\", \".\") as team_name, person_key from pacedb.task_status_fact_hist left join pacedb.plan_item_hist on pacedb.task_status_fact_hist.plan_item_key = pacedb.plan_item_hist.plan_item_key left join pacedb.data_block on pacedb.task_status_fact_hist.data_block_key = pacedb.data_block.data_block_key left join pacedb.team on pacedb.data_block.team_key = pacedb.team.team_key where wbs_element_key != 1 order by wbs_element_key");
tab_duration_info<-dbGetQuery(con, "select min(time_log_start_date) as start_date, DATE_FORMAT(min(time_log_start_date),'%Y%u') as start_week, max(time_log_end_date) as end_date, DATE_FORMAT(max(time_log_start_date),'%Y%u') as end_week, (DATE_FORMAT(max(time_log_start_date),'%Y%u')-DATE_FORMAT(min(time_log_start_date),'%Y%u')) as actual_weeks,wbs_element_key from pacedb.time_log_fact_hist join pacedb.plan_item_hist on pacedb.time_log_fact_hist.plan_item_key = pacedb.plan_item_hist.plan_item_key where time_log_fact_key != 23000 and wbs_element_key != 1 group by wbs_element_key")
tab_time_info<-dbGetQuery(con,"select wbs_element_key,phase_short_name,pacedb.phase.phase_key,phase_ordinal,min(task_actual_start_date_key) as task_begin_date, max(task_actual_complete_date_key) as task_end_date, sum(task_actual_time_minutes) as sum_actual_time,sum(task_plan_time_minutes) as sum_plan_time,phase_type from pacedb.task_status_fact_hist left join pacedb.plan_item_hist on pacedb.task_status_fact_hist.plan_item_key = pacedb.plan_item_hist.plan_item_key left join pacedb.phase on pacedb.plan_item_hist.phase_key = pacedb.phase.phase_key left join pacedb.phase_order on pacedb.phase.phase_key = pacedb.phase_order.phase_key where pacedb.phase.phase_key is not null group by wbs_element_key,phase_short_name order by wbs_element_key,phase_ordinal,pacedb.phase.phase_key")
tab_time_log_info<-dbGetQuery(con, "SELECT time_log_fact_key, wbs_element_key, time_log_delta_minutes, time_log_start_date, time_log_end_date, DATE_FORMAT(time_log_start_date, '%Y-%m-%d') as start_day, DATE_FORMAT(time_log_end_date, '%Y-%m-%d') as end_day, pacedb.plan_item_hist.phase_key, phase_short_name FROM pacedb.time_log_fact_hist left join pacedb.plan_item_hist on pacedb.time_log_fact_hist.plan_item_key = pacedb.plan_item_hist.plan_item_key left join pacedb.phase on pacedb.plan_item_hist.phase_key = pacedb.phase.phase_key where time_log_start_date > '1900-01-01 00:00:00' and time_log_end_date > '1900-01-01 00:00:00'")
tab_task_completion_info<-dbGetQuery(con, "SELECT task_date_fact_key, wbs_element_key, task_date_key, DATE_FORMAT(task_date_key, '%Y-%m-%d') as task_completion_date, measurement_type_key, phase_short_name FROM pacedb.task_date_fact_hist left join pacedb.plan_item_hist on pacedb.task_date_fact_hist.plan_item_key = pacedb.plan_item_hist.plan_item_key left join pacedb.phase on pacedb.plan_item_hist.phase_key = pacedb.phase.phase_key")
tab_ev_info<-dbGetQuery(con, "select wbs_element_key,pacedb.plan_item_hist.phase_key,phase_short_name,phase_type,task_actual_time_minutes,task_plan_time_minutes,task_actual_complete_date_key,task_date_key,measurement_type_key, defects_found from pacedb.task_status_fact_hist left join pacedb.task_date_fact_hist on pacedb.task_status_fact_hist.plan_item_key = pacedb.task_date_fact_hist.plan_item_key left join pacedb.plan_item_hist on pacedb.task_status_fact_hist.plan_item_key = pacedb.plan_item_hist.plan_item_key left join pacedb.phase on pacedb.plan_item_hist.phase_key = pacedb.phase.phase_key left join (select sum(defect_fix_count) as defects_found, plan_item_key from pacedb.defect_log_fact_hist group by plan_item_key) as defect_table on pacedb.defect_table.plan_item_key = pacedb.task_status_fact_hist.plan_item_key")
tab_bcws_info<-dbGetQuery(con, "SELECT wbs_element_key, SUM(s.task_plan_time_minutes) as sum_plan_minutes FROM task_status_fact s, task_date_fact d, measurement_type t, plan_item_hist h WHERE s.plan_item_key = d.plan_item_key AND s.data_block_key = d.data_block_key AND d.measurement_type_key = t.measurement_type_key AND t.measurement_type_name = 'Plan' AND d.task_date_key <= 29991231 AND s.plan_item_key = h.plan_item_key group by wbs_element_key")
tab_size_info<-dbGetQuery(con, "select wbs_element_key,measurement_type_key,size_metric_name,sum(size_added_and_modified) as sum_size_am,sum(size_added) as sum_size_added,sum(size_base) as sum_size_base,sum(size_deleted) as sum_size_deleted,sum(size_modified) as sum_size_modified,sum(size_reused) as sum_size_reused,sum(size_total) as sum_size_total from pacedb.size_fact_hist join pacedb.plan_item_hist on pacedb.size_fact_hist.plan_item_key = pacedb.plan_item_hist.plan_item_key join pacedb.size_metric on pacedb.size_fact_hist.size_metric_key = pacedb.size_metric.size_metric_key group by wbs_element_key,measurement_type_key,pacedb.size_fact_hist.size_metric_key");
tab_defect_injected_info<-dbGetQuery(con,"select wbs_element_key,sum(defect_fix_count) as sum_defect_fix_count,count(defect_log_fact_key) as sum_defect_records ,phase_short_name as defect_injected_phase_name from pacedb.defect_log_fact_hist left join pacedb.plan_item_hist on pacedb.defect_log_fact_hist.plan_item_key = pacedb.plan_item_hist.plan_item_key left join pacedb.phase on pacedb.defect_log_fact_hist.defect_injected_phase_key = pacedb.phase.phase_key group by wbs_element_key,defect_injected_phase_key")
tab_defect_removed_info<-dbGetQuery(con,"select wbs_element_key,sum(defect_fix_count) as sum_defect_fix_count,count(defect_log_fact_key) as sum_defect_records ,phase_short_name as defect_removed_phase_name from pacedb.defect_log_fact_hist left join pacedb.plan_item_hist on pacedb.defect_log_fact_hist.plan_item_key = pacedb.plan_item_hist.plan_item_key left join pacedb.phase on pacedb.defect_log_fact_hist.defect_removed_phase_key = pacedb.phase.phase_key group by wbs_element_key,defect_removed_phase_key")
tab_defect_fix_time_info<-dbGetQuery(con,"select wbs_element_key,pacedb.plan_item.phase_key,phase_short_name,sum(defect_fix_time_minutes) as sum_defect_fix_time from pacedb.defect_log_fact_hist left join pacedb.plan_item on pacedb.defect_log_fact_hist.plan_item_key = pacedb.plan_item.plan_item_key left join pacedb.phase on pacedb.plan_item.phase_key = pacedb.phase.phase_key group by wbs_element_key,phase_key")

# Read data selection from text file
fact_selection <- read.table("select_component-fact_data.txt", header=T, comment.char="#", sep=",")
fidelity_selection <- read.table("select_component-fidelity_data.txt", header=T, comment.char="#", sep=",")
selection_flgs <- list(fact_selection, fidelity_selection)
names(selection_flgs) <- c("fact_selection", "fidelity_selection")

# Get data frame for project fact and project process fidelity
DF_list <- list(tab_project_info, tab_process_info, tab_teams_info, tab_duration_info, tab_time_info, tab_time_log_info, tab_ev_info, tab_bcws_info, tab_size_info, tab_defect_injected_info, tab_defect_removed_info, tab_defect_fix_time_info, tab_task_completion_info, tab_wbs_info)
names(DF_list) <- c("tab_project_info", "tab_process_info", "tab_teams_info", "tab_duration_info", "tab_time_info", "tab_time_log_info", "tab_ev_info", "tab_bcws_info", "tab_size_info", "tab_defect_injected_info", "tab_defect_removed_info", "tab_defect_fix_time_info", "tab_task_completion_info", "tab_wbs_info") 
unit <- unique(tab_wbs_info$wbs_element_key)

source("getFactDataFrame.R")
getFactDataFrame(unit, DF_list, selection_flgs, currentDirectory, "component")
}